/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pt.ulisboa.tecnico.cmu.server;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
